cluster:
  -
    name: "GZ"
    title: "广州机房"
    note: "广州机房"
    db:
      driver: "mysql"
      host: "47.106.231.246"
      port: 30006
      userName: "root"
      password: "Key123qaz:mysql"
      database: "goku-ee-tmp"
    redis:
      mode: "stand"
      addrs: "47.95.203.198:6379"
      password: "Key123qazredis"
      dbIndex: 0
  #      masters: xxx,xxx
  -
    name: "BJ"
    title: "北京机房"
    note: "北京机房"
    db:
      driver: "mysql"
      host: "47.106.231.246"
      port: 30006
      userName: "root"
      password: "Key123qaz:mysql"
      database: "goku-ee-tmp"
    redis:
      mode: "stand"
      addrs: "47.95.203.198:6379"
      password: "Key123qazredis"
      dbIndex: 0
